package com.desksoft.wechat.common.model;

import java.util.Date;
import java.util.List;

import com.desksoft.wechat.common.model.base.BaseShutoffwaterflow;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shutoffwaterflow extends BaseShutoffwaterflow<Shutoffwaterflow> {
	public static final Shutoffwaterflow dao = new Shutoffwaterflow();
	
	public Page<Shutoffwaterflow> getShutoffwaterflowPaginateList(int pageNumber, int pageSize) {
		String SQL = "from shutoffwaterflow where isdelete = 1 ";
		SQL +=" order by createTime desc";
		return paginate(pageNumber, pageSize, "select *", SQL);
	}
	
	
	public boolean saveShutOffWaterJob(String keyword1,String keyword2,String keyword3,String remark){
		//state = 0 未执行 Job
		boolean flag = dao.set("keyword1", keyword1).set("keyword2", keyword2).set("keyword3", keyword3)
				.set("remark", remark).set("state", 0).
				set("createTime", new Date()).
				set("updateTime", new Date()).save();
		return flag;
	}
	
	public List<Shutoffwaterflow> getShutoffwaterflowList(int state){
		String sql = "select * from shutoffwaterflow where state=? order by createTime ASC";
		List<Shutoffwaterflow> list = dao.find(sql,state);
		return list;
	}
	
}
