package com.desksoft.wechat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserbindflow<M extends BaseUserbindflow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenID(java.lang.String openID) {
		set("openID", openID);
	}

	public java.lang.String getOpenID() {
		return get("openID");
	}

	public void setRePayFee(java.math.BigDecimal rePayFee) {
		set("rePayFee", rePayFee);
	}

	public java.math.BigDecimal getRePayFee() {
		return get("rePayFee");
	}

	public void setUserNo(java.lang.Integer userNo) {
		set("userNo", userNo);
	}

	public java.lang.Integer getUserNo() {
		return get("userNo");
	}

	public void setPhoneNum(java.lang.String phoneNum) {
		set("phoneNum", phoneNum);
	}

	public java.lang.String getPhoneNum() {
		return get("phoneNum");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setIsBinding(java.lang.Integer isBinding) {
		set("isBinding", isBinding);
	}

	public java.lang.Integer getIsBinding() {
		return get("isBinding");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
