package com.desksoft.wechat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayrecord<M extends BasePayrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUserNo(java.lang.Integer userNo) {
		set("userNo", userNo);
	}

	public java.lang.Integer getUserNo() {
		return get("userNo");
	}

	public void setFee(java.lang.Integer fee) {
		set("fee", fee);
	}

	public java.lang.Integer getFee() {
		return get("fee");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setIsChk(java.lang.Integer isChk) {
		set("isChk", isChk);
	}

	public java.lang.Integer getIsChk() {
		return get("isChk");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsPaySuccess(java.lang.Integer isPaySuccess) {
		set("isPaySuccess", isPaySuccess);
	}

	public java.lang.Integer getIsPaySuccess() {
		return get("isPaySuccess");
	}

	public void setOrderpayNo(java.lang.String orderpayNo) {
		set("orderpayNo", orderpayNo);
	}

	public java.lang.String getOrderpayNo() {
		return get("orderpayNo");
	}

	public void setRealNumber(java.lang.Long realNumber) {
		set("realNumber", realNumber);
	}

	public java.lang.Long getRealNumber() {
		return get("realNumber");
	}

	public void setFeeIDs(java.lang.String feeIDs) {
		set("feeIDs", feeIDs);
	}

	public java.lang.String getFeeIDs() {
		return get("feeIDs");
	}

}
